FROM ubuntu:20.04

RUN apt-get update
RUN apt-get upgrade --yes
RUN apt-get install git make python3 python3-pip opam --yes
ARG DEBIAN_FRONTEND=noninteractive
RUN TZ=Etc/UTC apt-get install texlive-full --yes
RUN pip3 install sphinx six
RUN opam init --disable-sandboxing
RUN opam switch create 5.0.0
RUN opam install dune menhir mdx --yes


WORKDIR /home
ADD "https://api.github.com/repos/pldi24-spectec/artifact/commits?per_page=1" latest_commit
RUN git clone https://github.com/pldi24-spectec/artifact.git
WORKDIR /home/artifact
RUN (cd spectec; eval $(opam env); make)


# Automate `eval $(opam env)`
ENTRYPOINT ["opam", "exec", "--"]
CMD ["/bin/bash", "--login"]
